# Generated by Django 5.1.5 on 2025-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('A', 'Asset'), ('L', 'Liability'), ('O', "Owner's Equity"), ('R', 'Revenue'), ('E', 'Expense')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
