# Generated by Django 5.1.5 on 2025-02-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_created_at_account_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('A', 'Asset'), ('L', 'Liability'), ('O', 'Owner Equity'), ('R', 'Revenue'), ('E', 'Expense')], max_length=20),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(choices=[('GJ', 'General'), ('AR', 'AR'), ('AP', 'AP'), ('SJ', 'SJ'), ('PJ', 'PJ')], default='GJ', max_length=20)),
                ('debit_credit', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=10)),
                ('is_posted', models.BooleanField(default=False)),
                ('post_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
            },
        ),
    ]
