# Generated by Django 5.1.6 on 2025-02-06 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transaction_alter_account_account_type_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
